version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_lms
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: new_password
      POSTGRES_DB: lms_db
    ports:
      - "5432:5432"
    volumes:

      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    container_name: mongodb_lms
    environment:
      MONGO_INITDB_DATABASE: lms_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: