version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_lms
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lms_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    container_name: mongodb_lms
    environment:
      MONGO_INITDB_DATABASE: lms_db2
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_lms
    depends_on:
      - postgres
      - mongodb
    ports:
      - "8445:8444"
    environment:
      SERVER_SSL_ENABLED : true
      SERVER_PORT : 8444
      SERVER_SSL_KEY-STORE : /app/config/keystore.p12
      SERVER_SSL_KEY-STORE-PASSWORD : password
      SERVER_SSL_KEY-STORE-TYPE : PKCS12
      SERVER_SSL_KEY-ALIAS : lmsapp
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lms_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: new_password
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: lms_db
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: password
    volumes:
      - ./keystore.p12:/app/config/keystore.p12

volumes:
  postgres_data:
  mongo_data:
