version: '3.9'

services:
  # Auth DBs
  postgres_auth:
    image: postgres:15
    container_name: postgres_auth
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lms_auth
    ports:
      - "5434:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    restart: always

  mongodb_auth:
    image: mongo:6.0
    container_name: mongodb_auth
    environment:
      MONGO_INITDB_DATABASE: lms_auth
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27019:27017"
    volumes:
      - mongo_auth_data:/data/db
    restart: always

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_auth:5432/lms_auth
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_MONGODB_HOST: mongodb_auth
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: lms_auth
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: password
    depends_on:
      - postgres_auth
      - mongodb_auth
    restart: unless-stopped

  # Course Service
  postgres_courses:
    image: postgres:15
    container_name: postgres_courses
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lms_course
    ports:
      - "5435:5432"
    volumes:
      - postgres_courses_data:/var/lib/postgresql/data
    restart: always

  courses_service:
    build:
      context: ./course_service
      dockerfile: Dockerfile
    container_name: courses_service
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_courses:5432/lms_course
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres_courses
    restart: unless-stopped

  # Assignment Service
  postgres_assignment:
    image: postgres:15
    container_name: postgres_assignment
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lms_assignment
    ports:
      - "5436:5432"
    volumes:
      - postgres_assignment_data:/var/lib/postgresql/data
    restart: always

  assignment_service:
    build:
      context: ./assignment_service
      dockerfile: Dockerfile
    container_name: assignment_service
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_assignment:5432/lms_assignment
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres_assignment
    restart: unless-stopped

  # Resource Service
  mongodb_resource:
    image: mongo:6.0
    container_name: mongodb_resource
    environment:
      MONGO_INITDB_DATABASE: lms_resource
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27020:27017"
    volumes:
      - mongo_resource_data:/data/db
    restart: always

  resource_service:
    build:
      context: ./resource_service
      dockerfile: Dockerfile
    container_name: resource_service
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      SPRING_DATA_MONGODB_HOST: mongodb_resource
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: lms_resource
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: password
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    depends_on:
      - mongodb_resource
    restart: unless-stopped

  # API Gateway
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "8090:8080"
    environment:
      SERVER_PORT: 8080
      AUTH_SERVICE_URL: http://auth_service:8081
      COURSE_SERVICE_URL: http://courses_service:8082
      ASSIGNMENT_SERVICE_URL: http://assignment_service:8083
      RESOURCE_SERVICE_URL: http://resource_service:8084
    depends_on:
      - auth_service
      - courses_service
      - assignment_service
      - resource_service
    restart: unless-stopped

volumes:
  postgres_auth_data:
  mongo_auth_data:
  postgres_courses_data:
  postgres_assignment_data:
  mongo_resource_data:
