services:
  # Eureka Server
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend-network
  # API Gateway
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "8090:8080"
    depends_on:
      - eureka-server
    networks:
      - backend-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

  # Auth Service
  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8091:8081"
    environment:
      SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_GROUP_ID: auth-service
      ZIPKIN_URL: http://zipkin:9411
    restart: unless-stopped
    depends_on:
      - eureka-server
    networks:
      - backend-network
  # Course Service
  course_service:
    build:
      context: ./course_service
      dockerfile: Dockerfile
    container_name: course_service
    ports:
      - "8092:8082"
    environment:
      SERVER_PORT: 8082
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_GROUP_ID: course-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      ZIPKIN_URL: http://zipkin:9411
    restart: unless-stopped
    depends_on:
      - eureka-server
    networks:
      - backend-network

  # Assignment Service
  assignment_service:
    build:
      context: ./assignment_service
      dockerfile: Dockerfile
    container_name: assignment_service
    ports:
      - "8093:8083"
    environment:
      SERVER_PORT: 8083
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_GROUP_ID: assignment-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      ZIPKIN_URL: http://zipkin:9411
    restart: unless-stopped
    depends_on:
      - eureka-server
    networks:
      - backend-network

  # Resource Service
  resource_service:
    build:
      context: ./resource_service
      dockerfile: Dockerfile
    container_name: resource_service
    ports:
      - "8094:8084"
    environment:
      SERVER_PORT: 8084
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_GROUP_ID: resource-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      ZIPKIN_URL: http://zipkin:9411
    restart: unless-stopped
    depends_on:
      - eureka-server
    networks:
      - backend-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
    networks:
      - backend-network
  #Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    restart: unless-stopped
    networks:
      - backend-network

  kafka-cli:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-cli
    depends_on:
      - kafka
    entrypoint: /bin/sh
    tty: true
    networks:
      - backend-network

  #Dashboards monitoring and k6 performance
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend-network

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Alex&030303
      - GF_PROVISIONING_ENABLED=true
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - backend-network


  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - backend-network

  k6:
    image: grafana/k6:latest
    container_name: monitoring_k6
    command: [ "run", "/k6/scripts/index.js" ]
    volumes:
      - ./k6:/k6
    working_dir: /k6/scripts
    networks:
      - backend-network



volumes:
  postgres_auth_data:
  mongo_auth_data:
  postgres_courses_data:
  postgres_assignment_data:
  mongo_resource_data:

networks:
  backend-network:
    driver: bridge