version: '3.8'

services:
  # API Gateway
  lms_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "8090:8080"
    environment:
      SERVER_PORT: "8080"
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    external: true