services:
  # API Gateway
  lms_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "8090:8080"
    environment:
      SERVER_PORT: 8080
      AUTH_SERVICE_URL: http://host.docker.internal:8091
      COURSE_SERVICE_URL: http://host.docker.internal:8092
      ASSIGNMENT_SERVICE_URL: http://host.docker.internal:8093
      RESOURCE_SERVICE_URL: http://host.docker.internal:8094
      # Eureka config
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    external: true
