services:
  # API Gateway
  lms_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "8090:8080"
    environment:
      SERVER_PORT: 8080
      AUTH_SERVICE_URL: http://localhost:8081
      COURSE_SERVICE_URL: http://localhost:8082
      ASSIGNMENT_SERVICE_URL: http://localhost:8083
      RESOURCE_SERVICE_URL: http://localhost:8084
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    external: true
