version: '3.9'

services:
  # API Gateway
  lms_gateway:
    build:
      context: ..
      dockerfile: api_gateway/Dockerfile
    container_name: api_gateway
    ports:
      - "8090:8080"
    environment:
      SERVER_PORT: 8080
      AUTH_SERVICE_URL: http://auth_service:8081
      COURSE_SERVICE_URL: http://course_service:8082
      ASSIGNMENT_SERVICE_URL: http://assignment_service:8083
      RESOURCE_SERVICE_URL: http://resource_service:8084
    restart: unless-stopped
    networks:
      - backend-network
    depends_on:
      - auth_service
      - course_service
      - assignment_service
      - resource_service

networks:
  backend-network:
    external: true