global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth_service:8091']

  - job_name: 'courses_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['course_service:8092']

  - job_name: 'assignment_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['assignment_service:8093']

  - job_name: 'resource_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource_service:8094']
