apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: registry.digitalocean.com/lms-registry333/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server.lms.svc.cluster.local:8761/eureka
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: APP_ALLOWED_ORIGINS
              value: http://localhost:3001
            - name: SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS_[/**]_ALLOWEDMETHODS
              value: GET,POST,PUT,DELETE,OPTIONS
            - name: SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS_[/**]_ALLOWEDHEADERS
              value: "*"
            - name: SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS_[/**]_ALLOWCREDENTIALS
              value: "true"
            - name: SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS_[/**]_EXPOSEDHEADERS
              value: Set-Cookie
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: lms
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
