apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: registry.digitalocean.com/lms-registry333/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server.lms.svc.cluster.local:8761/eureka
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.lms.svc.cluster.local:9092
            - name: KAFKA_GROUP_ID
              value: auth-service
            - name: ZIPKIN_URL
              value: http://zipkin.monitoring.svc.cluster.local:9411
            - name: APP_ALLOWED_ORIGINS
              value: http://localhost:3001,https://localhost:3001,https://lmsapi.software
            - name: APP_COOKIE_SECURE
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: lms
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
