apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: registry.digitalocean.com/lms-registry333/course-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.lms.svc.cluster.local:9092
            - name: KAFKA_GROUP_ID
              value: course-service
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: ZIPKIN_URL
              value: http://zipkin.monitoring.svc.cluster.local:9411
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: lms
spec:
  selector:
    app: course-service
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
