
services:
  # PostgreSQL Database for Course Service
  postgres_courses:
    image: postgres:15
    container_name: postgres_courses
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lms_course
    ports:
      - "5435:5432"
    volumes:
      - postgres_courses_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend-network

  # Course Service
  course_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_service
    ports:
      - "8092:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_courses:5432/lms_course
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_GROUP_ID: course-service
      # Eureka config
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    restart: unless-stopped
    depends_on:
      - postgres_courses
    networks:
      - backend-network

volumes:
  postgres_courses_data:

networks:
  backend-network:
    external: true
