name: LMS CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'auth_service/**'
      - 'course_service/**'
      - 'assignment_service/**'
      - 'resource_service/**'
      - 'api_gateway/**'
      - 'eureka-server/**'
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build all services
        run: |
          $services = @("eureka-server", "auth_service", "course_service", "assignment_service", "resource_service", "api_gateway")
          foreach ($service in $services) {
            Push-Location $service
            ./gradlew.bat clean build -x test
            Pop-Location
          }

      - name: List containers before stopping
        run: docker ps -a

      - name: Run tests
        run: |
          $services = @("eureka-server", "auth_service", "course_service", "assignment_service", "resource_service", "api_gateway")
          foreach ($service in $services) {
            Push-Location $service
            ./gradlew.bat test
            Pop-Location
          }

      - name: Ensure Docker is using Desktop context
        run: docker context use default
      - name: Stop only if containers are running
        run: |
          if (docker ps -q) {
            docker compose down -v
          } else {
            Write-Host "No running containers to stop"
          }

      - name: Docker Compose Build (all services)
        run: docker compose build --no-cache

      - name: Docker Compose Up (start all)
        run: docker compose up -d
