name: Microservices CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      # Build each service individually
      - name: Build Auth Service
        run: ./gradlew :auth_service:clean :auth_service:build

      - name: Build Course Service
        run: ./gradlew :course_service:clean :course_service:build

      - name: Build Assignment Service
        run: ./gradlew :assignment_service:clean :assignment_service:build

      - name: Build Resource Service
        run: ./gradlew :resource_service:clean :resource_service:build

      - name: Build API Gateway
        run: ./gradlew :api_gateway:clean :api_gateway:build

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 1: Build updated Docker images (force rebuild using correct JARs)
      - name: Build Docker images
        run: |
          docker compose -f auth_service/docker-compose.auth.yml build --no-cache
          docker compose -f course_service/docker-compose.course.yml build --no-cache
          docker compose -f assignment_service/docker-compose.assignment.yml build --no-cache
          docker compose -f resource_service/docker-compose.resource.yml build --no-cache
          docker compose -f api_gateway/docker-compose.gateway.yml build --no-cache

      # Step 2: Recreate running containers with updated images
      - name: Run Docker containers
        run: |
          docker network create backend-network || true
          docker compose -f auth_service/docker-compose.auth.yml up -d --force-recreate
          docker compose -f course_service/docker-compose.course.yml up -d --force-recreate
          docker compose -f assignment_service/docker-compose.assignment.yml up -d --force-recreate
          docker compose -f resource_service/docker-compose.resource.yml up -d --force-recreate
          docker compose -f api_gateway/docker-compose.gateway.yml up -d --force-recreate

      - name: Wait for services to start
        run: sleep 20

      # Optional: Add integration tests here
