name: Microservices CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'auth_service/**'
      - 'course_service/**'
      - 'assignment_service/**'
      - 'resource_service/**'
      - 'api_gateway/**'
      - 'eureka-server/**'

jobs:
  eureka-server:
    if: ${{ contains(github.event.head_commit.message, '[gateway]') || contains(github.event.head_commit.message, 'eureka-server/') }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build Eureka Server JAR
        run: |
          cd eureka-server
          ./gradlew.bat clean build -x test
        shell: pwsh

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: eureka-jar
          path: eureka-server/build/libs/*.jar

      - name: Download JAR for Docker build
        uses: actions/download-artifact@v3
        with:
          name: eureka-jar
          path: eureka-server/build/libs

      - name: Build & Deploy Eureka
        run: |
          docker compose -f docker-compose.services.yml down --remove-orphans eureka-server
          docker compose -f docker-compose.services.yml build eureka-server --no-cache
          docker compose -f docker-compose.services.yml up -d eureka-server
        shell: pwsh

  auth-service:
    if: ${{ contains(github.event.head_commit.message, '[auth]') || contains(github.event.head_commit.message, 'auth_service/') }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Test Auth Service
        run: |
          cd auth_service
          ./gradlew.bat test
        shell: pwsh

      - name: Build Auth Service JAR
        run: |
          cd auth_service
          ./gradlew.bat clean build -x test
        shell: pwsh

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: auth-jar
          path: auth_service/build/libs/*.jar

      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: auth-jar
          path: auth_service/build/libs

      - name: Build & Deploy Auth
        run: |
          docker compose -f docker-compose.services.yml down --remove-orphans auth_service
          docker compose -f docker-compose.services.yml build auth_service --no-cache
          docker compose -f docker-compose.services.yml up -d auth_service
        shell: pwsh

  course-service:
    if: ${{ contains(github.event.head_commit.message, '[course]') || contains(github.event.head_commit.message, 'course_service/') }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Test Course Service
        run: |
          cd course_service
          ./gradlew.bat test
        shell: pwsh

      - name: Build JAR
        run: |
          cd course_service
          ./gradlew.bat clean build -x test
        shell: pwsh

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: course-jar
          path: course_service/build/libs/*.jar

      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: course-jar
          path: course_service/build/libs

      - name: Build & Deploy Course
        run: |
          docker compose -f docker-compose.services.yml down --remove-orphans course_service
          docker compose -f docker-compose.services.yml build course_service --no-cache
          docker compose -f docker-compose.services.yml up -d course_service
        shell: pwsh

  assignment-service:
    if: ${{ contains(github.event.head_commit.message, '[assignment]') || contains(github.event.head_commit.message, 'assignment_service/') }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Test Assignment Service
        run: |
          cd assignment_service
          ./gradlew.bat test
        shell: pwsh

      - name: Build JAR
        run: |
          cd assignment_service
          ./gradlew.bat clean build -x test
        shell: pwsh

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: assignment-jar
          path: assignment_service/build/libs/*.jar

      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: assignment-jar
          path: assignment_service/build/libs

      - name: Build & Deploy Assignment
        run: |
          docker compose -f docker-compose.services.yml down --remove-orphans assignment_service
          docker compose -f docker-compose.services.yml build assignment_service --no-cache
          docker compose -f docker-compose.services.yml up -d assignment_service
        shell: pwsh

  resource-service:
    if: ${{ contains(github.event.head_commit.message, '[resource]') || contains(github.event.head_commit.message, 'resource_service/') }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Test Resource Service
        run: |
          cd resource_service
          ./gradlew.bat test --tests "com.lms.resource_service.unit_tests.*"
        shell: pwsh

      - name: Build JAR
        run: |
          cd resource_service
          ./gradlew.bat clean build -x test
        shell: pwsh

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: resource-jar
          path: resource_service/build/libs/*.jar

      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: resource-jar
          path: resource_service/build/libs

      - name: Build & Deploy Resource
        run: |
          docker compose -f docker-compose.services.yml down --remove-orphans resource_service
          docker compose -f docker-compose.services.yml build resource_service --no-cache
          docker compose -f docker-compose.services.yml up -d resource_service
        shell: pwsh

  gateway:
    needs:
      - eureka-server
      - auth-service
      - course-service
      - assignment-service
      - resource-service
    if: ${{ contains(github.event.head_commit.message, '[gateway]') || contains(github.event.head_commit.message, 'api_gateway/') }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Test API Gateway
        run: |
          cd api_gateway
          ./gradlew.bat test
        shell: pwsh

      - name: Build JAR
        run: |
          cd api_gateway
          ./gradlew.bat clean build -x test
        shell: pwsh

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: gateway-jar
          path: api_gateway/build/libs/*.jar

      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: gateway-jar
          path: api_gateway/build/libs

      - name: Build & Deploy API Gateway
        run: |
          docker compose -f docker-compose.services.yml down --remove-orphans api_gateway
          docker compose -f docker-compose.services.yml build api_gateway --no-cache
          docker compose -f docker-compose.services.yml up -d api_gateway
        shell: pwsh
