name: Microservices CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Make Gradlew executable
        run: |
          chmod +x auth_service/gradlew
          chmod +x course_service/gradlew
          chmod +x assignment_service/gradlew
          chmod +x resource_service/gradlew
          chmod +x api_gateway/gradlew

      # 🔨 Build JARs from each service folder
      - name: Build Auth Service
        run: cd auth_service && ./gradlew clean build

      - name: Build Course Service
        run: cd course_service && ./gradlew clean build

      - name: Build Assignment Service
        run: cd assignment_service && ./gradlew clean build

      - name: Build Resource Service
        run: cd resource_service && ./gradlew clean build

      - name: Build API Gateway
        run: cd api_gateway && ./gradlew clean build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🔧 Build Docker images with updated JARs
      - name: Build Docker images
        run: |
          docker compose -f auth_service/docker-compose.auth.yml build --no-cache
          docker compose -f course_service/docker-compose.course.yml build --no-cache
          docker compose -f assignment_service/docker-compose.assignment.yml build --no-cache
          docker compose -f resource_service/docker-compose.resource.yml build --no-cache
          docker compose -f api_gateway/docker-compose.gateway.yml build --no-cache

      # 🚀 Run containers with updated images
      - name: Run Docker containers
        run: |
          docker network create backend-network || true
          docker compose -f auth_service/docker-compose.auth.yml up -d --force-recreate
          docker compose -f course_service/docker-compose.course.yml up -d --force-recreate
          docker compose -f assignment_service/docker-compose.assignment.yml up -d --force-recreate
          docker compose -f resource_service/docker-compose.resource.yml up -d --force-recreate
          docker compose -f api_gateway/docker-compose.gateway.yml up -d --force-recreate

      - name: Wait for services to start
        run: sleep 20
