name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: new_password
          POSTGRES_DB: lms_db
      mongo:
        image: mongo:6.0
        ports:
          - 27018:27017
        env:
          MONGO_INITDB_DATABASE: lms_db2
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Wait for PostgreSQL and MongoDB
      - name: Wait for PostgreSQL
        run: |
          until nc -z localhost 5433; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
      - name: Wait for MongoDB
        run: |
          until nc -z localhost 27018; do
            echo "Waiting for MongoDB..."
            sleep 1
          done
      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # Make Gradlew executable
      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      # Build the backend
      - name: Build Backend
        run: ./gradlew build

      # Verify JAR file exists
      - name: Verify JAR file
        run: ls -la build/libs

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/*.jar

  dockerize:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/libs

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/backend:latest ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
