name: Microservices CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-auth:
    name: Build Auth Service
    runs-on: self-hosted
    if: github.repository == 'AlexIvan333/LMS-BackEnd'
    paths:
      - 'auth_service/**'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build Auth
        run: |
          cd auth_service
          ./gradlew clean build -x test
          cd ..
          docker compose -f auth_service/docker-compose.auth.yml down -v || true
          docker compose -f auth_service/docker-compose.auth.yml build --no-cache
          docker compose -f auth_service/docker-compose.auth.yml up -d

  build-course:
    name: Build Course Service
    runs-on: self-hosted
    paths:
      - 'course_service/**'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build Course
        run: |
          cd course_service
          ./gradlew clean build -x test
          cd ..
          docker compose -f course_service/docker-compose.course.yml down -v || true
          docker compose -f course_service/docker-compose.course.yml build --no-cache
          docker compose -f course_service/docker-compose.course.yml up -d

  build-assignment:
    name: Build Assignment Service
    runs-on: self-hosted
    paths:
      - 'assignment_service/**'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build Assignment
        run: |
          cd assignment_service
          ./gradlew clean build -x test
          cd ..
          docker compose -f assignment_service/docker-compose.assignment.yml down -v || true
          docker compose -f assignment_service/docker-compose.assignment.yml build --no-cache
          docker compose -f assignment_service/docker-compose.assignment.yml up -d

  build-resource:
    name: Build Resource Service
    runs-on: self-hosted
    paths:
      - 'resource_service/**'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build Resource
        run: |
          cd resource_service
          ./gradlew clean build -x test
          cd ..
          docker compose -f resource_service/docker-compose.resource.yml down -v || true
          docker compose -f resource_service/docker-compose.resource.yml build --no-cache
          docker compose -f resource_service/docker-compose.resource.yml up -d

  build-gateway:
    name: Build API Gateway
    runs-on: self-hosted
    paths:
      - 'api_gateway/**'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build Gateway
        run: |
          cd api_gateway
          ./gradlew clean build -x test
          cd ..
          docker compose -f api_gateway/docker-compose.gateway.yml down -v || true
          docker compose -f api_gateway/docker-compose.gateway.yml build --no-cache
          docker compose -f api_gateway/docker-compose.gateway.yml up -d
