name: Microservices CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # ========================
      # AUTH SERVICE
      # ========================
      - name: Build Auth Service
        if: ${{ contains(join(github.event.commits.*.modified, ',') , 'auth_service/') || contains(join(github.event.commits.*.added, ',') , 'auth_service/') || contains(join(github.event.commits.*.renamed, ','), 'auth_service/') }}
        run: |
          cd auth_service
          ./gradlew clean build -x test
          cd ..
          docker compose -f auth_service/docker-compose.auth.yml down -v || true
          docker compose -f auth_service/docker-compose.auth.yml build --no-cache
          docker compose -f auth_service/docker-compose.auth.yml up -d

      # ========================
      # COURSE SERVICE
      # ========================
      - name: Build Course Service
        if: ${{ contains(join(github.event.commits.*.modified, ',') , 'course_service/') || contains(join(github.event.commits.*.added, ',') , 'course_service/') || contains(join(github.event.commits.*.renamed, ','), 'course_service/') }}
        run: |
          cd course_service
          ./gradlew clean build -x test
          cd ..
          docker compose -f course_service/docker-compose.course.yml down -v || true
          docker compose -f course_service/docker-compose.course.yml build --no-cache
          docker compose -f course_service/docker-compose.course.yml up -d

      # ========================
      # ASSIGNMENT SERVICE
      # ========================
      - name: Build Assignment Service
        if: ${{ contains(join(github.event.commits.*.modified, ',') , 'assignment_service/') || contains(join(github.event.commits.*.added, ',') , 'assignment_service/') || contains(join(github.event.commits.*.renamed, ','), 'assignment_service/') }}
        run: |
          cd assignment_service
          ./gradlew clean build -x test
          cd ..
          docker compose -f assignment_service/docker-compose.assignment.yml down -v || true
          docker compose -f assignment_service/docker-compose.assignment.yml build --no-cache
          docker compose -f assignment_service/docker-compose.assignment.yml up -d

      # ========================
      # RESOURCE SERVICE
      # ========================
      - name: Build Resource Service
        if: ${{ contains(join(github.event.commits.*.modified, ',') , 'resource_service/') || contains(join(github.event.commits.*.added, ',') , 'resource_service/') || contains(join(github.event.commits.*.renamed, ','), 'resource_service/') }}
        run: |
          cd resource_service
          ./gradlew clean build -x test
          cd ..
          docker compose -f resource_service/docker-compose.resource.yml down -v || true
          docker compose -f resource_service/docker-compose.resource.yml build --no-cache
          docker compose -f resource_service/docker-compose.resource.yml up -d

      # ========================
      # API GATEWAY
      # ========================
      - name: Build API Gateway
        if: ${{ contains(join(github.event.commits.*.modified, ',') , 'api_gateway/') || contains(join(github.event.commits.*.added, ',') , 'api_gateway/') || contains(join(github.event.commits.*.renamed, ','), 'api_gateway/') }}
        run: |
          cd api_gateway
          ./gradlew clean build -x test
          cd ..
          docker compose -f api_gateway/docker-compose.gateway.yml down -v || true
          docker compose -f api_gateway/docker-compose.gateway.yml build --no-cache
          docker compose -f api_gateway/docker-compose.gateway.yml up -d

      # ========================
      # Show active containers
      # ========================
      - name: Show running containers
        run: docker ps -a
