name: Microservices CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/*.jar

  dockerize:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/libs

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build all services
        run: |
          docker compose -f docker-compose.auth.yml build
          docker compose -f docker-compose.course.yml build
          docker compose -f docker-compose.assignment.yml build
          docker compose -f docker-compose.resource.yml build
          docker compose -f docker-compose.gateway.yml build

      # Optional: Push images if desired
      # - name: Push images to Docker Hub
      #   run: |
      #     docker tag auth_service yourname/auth_service:latest
      #     docker push yourname/auth_service:latest
      #     # repeat for other services

      - name: Run all services
        run: |
          docker network create backend-network || true
          docker compose -f docker-compose.auth.yml up -d
          docker compose -f docker-compose.course.yml up -d
          docker compose -f docker-compose.assignment.yml up -d
          docker compose -f docker-compose.resource.yml up -d
          docker compose -f docker-compose.gateway.yml up -d

      - name: Wait for services to start
        run: sleep 20

      # Optionally run integration tests here

      - name: Tear down containers
        if: always()
        run: |
          docker compose -f docker-compose.gateway.yml down
          docker compose -f docker-compose.resource.yml down
          docker compose -f docker-compose.assignment.yml down
          docker compose -f docker-compose.course.yml down
          docker compose -f docker-compose.auth.yml down
